# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SGPicture' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SGPicture
  pod 'AFNetworking', '~> 3.1.0’
  pod 'Masonry', '~> 0.6.4'
  
  target 'SGPictureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SGPictureUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
